sudo: false
dist: trusty
language: ruby
rvm:
  - '2.3.8'
  - '2.4.9'
  - '2.5.7'
  - '2.6.5'
  - '2.7.0'
  - 'jruby-9.1.17.0'
  - 'jruby-9.2.7.0'
before_script:
  - env
  - rvm debug
script:
  - bundle exec rspec
  - bundle exec travis_check_rubies
