sudo: false
language: ruby
rvm:
  - '2.0.0-p648'
  - '2.1.10'
  - '2.2.10'
  - '2.3.7'
  - '2.4.4'
  - '2.5.1'
  - 'jruby-9.0.5.0'
  - 'jruby-9.1.9.0'
before_script:
  - env
  - rvm debug
script:
  - bundle exec rspec
  - bundle exec travis_check_rubies
matrix:
  allow_failures:
    - rvm: 'jruby-9.0.5.0'
  exclude:
    - rvm: 'jruby-9.0.5.0'
  include:
    - rvm: 'jruby-9.0.5.0'
