sudo: false
language: ruby
rvm:
  - '2.3.8'
  - '2.4.5'
  - '2.5.5'
  - '2.6.2'
  - 'jruby-9.1.9.0'
before_script:
  - env
  - rvm debug
script:
  - bundle exec rspec
  - bundle exec travis_check_rubies
