sudo: false
language: ruby
rvm:
  - '1.8.7-p371'
  - '1.9.3-p551'
  - '2.0.0-p648'
  - '2.1.10'
  - '2.2.6'
  - '2.3.3'
  - '2.4.0'
  - 'jruby-1.7.26'
  - 'jruby-9.0.5.0'
  - 'jruby-9.1.5.0'
script:
  - bundle exec rspec
  - bundle exec travis_check_rubies
matrix:
  allow_failures:
    - rvm: 'jruby-9.0.5.0'
  exclude:
    - rvm: 'jruby-9.0.5.0'
  include:
    - rvm: 'jruby-9.0.5.0'
